// const sectionsAnimais = document.querySelectorAll('.animais-descricao section');
// console.log(sectionsAnimais);

import initScrollSuave from './modules/scroll-suave.js';
import initScrollSite from './modules/animacao-scroll.js';
import initAccordion from './modules/accordion.js';
import initTabNav from './modules/animacao-tabnav-menu.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropDown from './modules/dropdown.js';
import initMobile from './modules/mobile-menu.js';
import initDate from './modules/date-object.js';
import initFetch from './modules/fetchAnimais.js';
import initBitcoin from './modules/bitcoin.js';
initScrollSuave();
initScrollSite();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropDown();
initMobile();
initDate();
initFetch();
initBitcoin();
